CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_MIPI_DBI=y
CONFIG_SSD1681=y
CONFIG_DISPLAY=y
CONFIG_DISPLAY_BUFFER=y
CONFIG_DISPLAY_BUFFER_SIZE=5000
CONFIG_LOG=y
CONFIG_PRINTK=y

CONFIG_DEBUG=y
CONFIG_DEBUG_INFO=y
CONFIG_EXCEPTION_STACK_TRACE=y
CONFIG_ASSERT=y
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y
CONFIG_RESET_ON_FATAL_ERROR=n

CONFIG_SPI_STM32_INTERRUPT=n
CONFIG_SPI_STM32_DMA=n

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_ISR_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
